### ISSUE TITLE
"Rendering" and "Load times" charts are empty

### ISSUE THREAD

**Issue by pltnkv** [speedtracker/speedtracker#33]
Can you help with it?
Dashboard here: https://pltnkv.github.io/speedtracker/

**Comment by pothi** [comment]
Ref: https://www.webpagetest.org/result/170303_3V_4B7/1/details/

Could it be due to the fact that the test didn't complete successfully?

Please try the following...

- create a new profile at https://github.com/pltnkv/speedtracker/tree/master/_profiles (copy / paste to a new file name)
- change the URL to https://github.com/pltnkv/speedtracker/blob/master/_profiles/default.html#L28 to some random URL on the web (such as GitHub.com). Please change other other options that deemed fit.
- manual trigger a test (the result would contain the test ID; make sure the test completes in wpt .org)
- see if you can see the rendering and 'load times' charts for the *new* url.

**Comment by pltnkv** [comment]
In new profile to github.com it works.
https://pltnkv.github.io/speedtracker/test/?period=week

Sorry, i didn't understand why test did not complete successfully.
Ref: https://www.webpagetest.org/result/170303_3V_4B7/1/details/
Here _Load Time_ is 14.134s
What is indicator of successful complete?

When i run test directly from webpagetest it takes about two minutes.
May it be connected with opened websockect connection on the page?
Can we rely on "Interactive (beta)" timing?

**Comment by pothi** [comment]
> What is indicator of successful complete?

In the WPT result, the column named "Result (error code)" would be zero on successful completion.

**Comment by pltnkv** [comment]
Thanks, I fix pending request in the app try again

**Comment by eduardoboucas** [comment]
@pltnkv I see a lot of `null` values in the [result file](https://github.com/pltnkv/speedtracker/blob/master/results/default/2017/03.json) for your default profile. I've never seen this before, and it's odd because theoretically SpeedTracker should just be using whatever values come back from the WebPageTest API result.

Could you try deleting the `results` directory and manually running a test again?

**Comment by pltnkv** [comment]
It work after I removed the pending request:
https://pltnkv.github.io/speedtracker/default/?period=week

Thanks! You made awesome tool

**Comment by pothi** [comment]
Glad to know, it works now. Kindly close the issue when you get a chance. Thanks.
